#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$REPO_ROOT"

COMMON_UI_LIB="${SCRIPT_DIR}/common_ui.sh"
if [[ ! -f "$COMMON_UI_LIB" ]]; then
  echo "Missing global UI library: ${COMMON_UI_LIB}"
  exit 1
fi
source "$COMMON_UI_LIB"

CURRENT_SCRIPT="$(basename "$0")"

validate_test_dir() {
  local test_dir="$1"
  [[ -d "$test_dir/query" && -d "$test_dir/gallery" ]]
}

default_test_dir_by_tag() {
  local tag="$1"
  case "$tag" in
    market) printf './data/Market/pytorch\n' ;;
    duke) printf './data/Duke/pytorch\n' ;;
    msmt) printf './data/MSMT/pytorch\n' ;;
    cub) printf './data/CUB/pytorch\n' ;;
    vehicleid) printf './data/VehicleID/pytorch\n' ;;
    veri) printf './data/VeRi/pytorch\n' ;;
    viper) printf './data/VIPeR/pytorch\n' ;;
    *) printf '' ;;
  esac
}

extract_dataset_tag_from_mat() {
  local mat_path="$1"
  local base
  base="$(basename "$mat_path")"
  base="${base#pytorch_result_}"
  base="${base%.mat}"
  printf '%s\n' "$base"
}

build_model_candidates() {
  local model_root="./model"
  local model_dir=""
  local model_name=""

  MODEL_NAMES=()
  MODEL_DESCS=()
  SKIPPED_MODELS=()

  if [[ ! -d "$model_root" ]]; then
    return 1
  fi

  for model_dir in "$model_root"/*; do
    [[ -d "$model_dir" ]] || continue
    model_name="$(basename "$model_dir")"
    if compgen -G "${model_dir}/pytorch_result_*.mat" > /dev/null; then
      MODEL_NAMES+=("$model_name")
      MODEL_DESCS+=("${model_name}")
    else
      SKIPPED_MODELS+=("$model_name")
    fi
  done

  [[ ${#MODEL_NAMES[@]} -gt 0 ]]
}

clear
ui_banner "$CURRENT_SCRIPT"

ui_info "Scanning models with cached result mats..."
MODEL_NAMES=()
MODEL_DESCS=()
SKIPPED_MODELS=()
if ! build_model_candidates; then
  ui_error "No model with pytorch_result_*.mat found under ./model."
  ui_tip "Run test.py first to generate result mats."
  exit 1
fi
model_choice=""
model_label=""
default_model_idx="${#MODEL_NAMES[@]}"
ui_select model_choice model_label "Select the model for demo:" "$default_model_idx" "${MODEL_DESCS[@]}"
selected_model_idx=$((model_choice - 1))
name="${MODEL_NAMES[$selected_model_idx]}"
model_path="./model/${name}"

mapfile -t MAT_FILES < <(find "$model_path" -maxdepth 1 -type f -name 'pytorch_result_*.mat' | sort)
if [[ ${#MAT_FILES[@]} -eq 0 ]]; then
  ui_error "No pytorch_result_*.mat found in ${model_path}."
  ui_tip "Run test.py for this model first, then retry demo.sh."
  exit 1
fi

MAT_DESCS=()
for mat in "${MAT_FILES[@]}"; do
  MAT_DESCS+=("$(basename "$mat")")
done

mat_choice=""
mat_label=""
ui_select mat_choice mat_label "Select result mat:" "1" "${MAT_DESCS[@]}"
selected_mat="${MAT_FILES[$((mat_choice - 1))]}"
if [[ ! -f "$selected_mat" ]]; then
  ui_error "Selected mat does not exist: ${selected_mat}"
  exit 1
fi
dataset_tag="$(extract_dataset_tag_from_mat "$selected_mat")"

test_dir="$(default_test_dir_by_tag "$dataset_tag")"
if [[ -z "$test_dir" ]]; then
  ui_warn "Unknown dataset tag '${dataset_tag}'. Please input test_dir manually."
  ui_input test_dir "test_dir" "./data/Market/pytorch"
fi

if ! validate_test_dir "$test_dir"; then
  ui_error "Invalid test_dir: ${test_dir}"
  ui_tip "Required folders are missing: ${test_dir}/query and ${test_dir}/gallery"
  exit 1
fi

if ! query_count="$(python - "$selected_mat" <<'PY'
import scipy.io
import sys

mat_path = sys.argv[1]
try:
  result = scipy.io.loadmat(mat_path)
except Exception as exc:
  print(f"ERROR: failed to load mat: {exc}")
  raise SystemExit(2)

if 'query_label' not in result:
  print("ERROR: missing key 'query_label' in mat.")
  raise SystemExit(3)

query_label = result['query_label']
try:
  print(len(query_label[0]))
except Exception as exc:
  print(f"ERROR: invalid query_label format: {exc}")
  raise SystemExit(4)
PY
)"; then
  ui_error "Failed to parse query count from ${selected_mat}."
  ui_tip "Ensure this mat is generated by test.py and contains key 'query_label'."
  exit 1
fi

if [[ ! "$query_count" =~ ^[0-9]+$ ]] || (( query_count <= 0 )); then
  ui_error "Invalid query count parsed from ${selected_mat}: ${query_count}"
  exit 1
fi

max_query_index=$((query_count - 1))
ui_info "Query index range: 0 ~ ${max_query_index}"
ui_input query_index "query_index" "0" '^[0-9]+$' "v >= 0 && v < ${query_count}" "Invalid query_index: expected 0 ~ ${max_query_index}."

python demo.py --result_mat "$selected_mat" --test_dir "$test_dir" --query_index "$query_index"
